import type productCard from "@/domain/home/productCard.interface";

export let productCards: productCard[] = [
  {
    idx: 1,
    profile_img: "red",
    nickname: "리진오",
    certified: true,
    category: "gameMoney",
    uploadTime: "10분 전",
    game: "DK모바일오리진",
    server: "S1디오네",
    title: "100억 플로린 팝니다. 50억까지 한방",
    minQty: 1000000000,
    maxQty: 10000000000,
    unit: "게임머니",
    price: 9300,
    chatQty: 10,
    likeQty: 5,
  },
  {
    idx: 2,
    profile_img: "yellow",
    nickname: "아이템천사",
    certified: true,
    category: "gameMoney",
    uploadTime: "3시간 전",
    game: "메이플스토리",
    server: "아케인",
    title: "한국인이 판매하는 안전/스피드 메소",
    minQty: 10000000000,
    maxQty: 30000000000,
    unit: "게임머니",
    price: 140,
    chatQty: 20,
    likeQty: 5,
  },
  {
    idx: 3,
    profile_img: "green",
    nickname: "아이템파는이템",
    certified: true,
    category: "item",
    uploadTime: "3시간 전",
    game: "디아블로2:레저렉션",
    server: "노말",
    title:
      " 스탠최저가/완전최저가가격비교 당일최저가 소서,팔라,바바,아마,네크,드루",
    minQty: 8,
    maxQty: 945238,
    unit: "개",
    price: 1000,
    chatQty: 20,
    likeQty: 5,
  },
  {
    idx: 4,
    profile_img: "yellow",
    nickname: "리니지작업장",
    certified: true,
    category: "item",
    uploadTime: "4시간 전",
    game: "리니지2",
    server: "불멸",
    title: "축7스턴건틀렛 팝니다 급처",
    minQty: 1,
    maxQty: 1,
    unit: "개",
    price: 600000,
    chatQty: 120,
    likeQty: 10,
  },
  {
    idx: 5,
    profile_img: "green",
    nickname: "카레맛피자",
    certified: true,
    category: "character",
    uploadTime: "7시간 전",
    game: "리니지M",
    server: "서버전체",
    title: "87 뇌신 5영스 뱀파",
    minQty: 1,
    maxQty: 1,
    unit: "개",
    price: 300000,
    chatQty: 2,
    likeQty: 5,
  },
  {
    idx: 6,
    profile_img: "red",
    nickname: "슬리어건케인",
    certified: true,
    category: "character",
    uploadTime: "7시간 전",
    game: "V4",
    server: "서버전체",
    title: "더트4아크메이지팝니다",
    minQty: 1,
    maxQty: 1,
    unit: "개",
    price: 2500000,
    chatQty: 102,
    likeQty: 6,
  },
  {
    idx: 7,
    profile_img: "yellow",
    nickname: "문상마",
    certified: true,
    category: "etc",
    uploadTime: "9시간 전",
    game: "기타",
    server: "기타",
    title: "문상 5000원 분할 판매합니다.",
    minQty: 1,
    maxQty: 10,
    unit: "개",
    price: 4500,
    chatQty: 2,
    likeQty: 7,
  },
  {
    idx: 8,
    profile_img: "green",
    nickname: "상품권마",
    certified: true,
    category: "etc",
    uploadTime: "하루 전",
    game: "기타",
    server: "기타",
    title: "신세계 상품권 10만원 급매합니다.",
    minQty: 1,
    maxQty: 10,
    unit: "개",
    price: 98000,
    chatQty: 2,
    likeQty: 6,
  },
];

export default productCards;
